// Snipe-IT model list, exported 2026-08-27. Edit this list any time — no build step needed.
// Regenerate by re-exporting Models from Snipe-IT and updating the entries below.
const ASSET_MODELS = [
  { name: "300e", modelNumber: "81H0", category: "Chromebook" },
  { name: "XGS3300", modelNumber: "XGS3300", category: "Network Infrastructure" },
  { name: "Chromebook 3110", modelNumber: "Chromebook 3110", category: "Chromebook" },
  { name: "2920-48G-POE+", modelNumber: "J9729A", category: "Network Infrastructure" },
  { name: "Chromebook 3100", modelNumber: "", category: "Chromebook" },
  { name: "Laserjet 4001dn", modelNumber: "4001dn", category: "Printer" },
  { name: "Laserjet 4201dn", modelNumber: "4201dn", category: "Printer" },
  { name: "Optiplex 3090", modelNumber: "Optiplex 3090", category: "Desktop Computer" },
  { name: "6940", modelNumber: "6940", category: "Phone" },
  { name: "6920", modelNumber: "6920", category: "Phone" },
  { name: "Optiplex 5490 AIO", modelNumber: "", category: "Desktop Computer" },
  { name: "P2312H", modelNumber: "P2312H", category: "Monitor" },
  { name: "P2311H", modelNumber: "P2311H", category: "Monitor" },
  { name: "SBID-MX075-V4", modelNumber: "SBID-MX075-V4", category: "Interactive Flat Panel" },
  { name: "V4K", modelNumber: "V4K", category: "Document Camera" },
  { name: "Smart MX065-V3", modelNumber: "MX065-V3", category: "Interactive Flat Panel" },
  { name: "Chromebook HP -X360 11 G3", modelNumber: "X360 11 G3", category: "Chromebook" },
  { name: "SMART MX075-V5", modelNumber: "MX075-V5", category: "Interactive Flat Panel" },
  { name: "IPEVO Basic", modelNumber: "-", category: "Document Camera" },
  { name: "Epson Powerlite 580", modelNumber: "Powerlite 580", category: "Projector" },
  { name: "SmartBoard M600", modelNumber: "M600", category: "Interactive Flat Panel" },
  { name: "Epson Powerlite 680", modelNumber: "Powerlite 680", category: "Projector" },
  { name: "SmartBoard SB680-M2", modelNumber: "SB680-M2", category: "Interactive Flat Panel" },
  { name: "Samsung TV 32\"", modelNumber: "UN32J5003AF", category: "Televison" },
  { name: "Dell Latitude 3520", modelNumber: "Latitude 3520", category: "Laptop Computer" },
  { name: "Dell 3050", modelNumber: "3050", category: "AIO Computer" },
  { name: "Vizio 55\" Tv", modelNumber: "D55D2", category: "Televison" },
  { name: "Dell Optiplex 3020", modelNumber: "3020", category: "Desktop Computer" },
  { name: "Dell Optiplex", modelNumber: "Optiplex 7090", category: "Desktop Computer" },
  { name: "IPEVO HD", modelNumber: "HS", category: "Document Camera" },
  { name: "Dell Optiplex 3280", modelNumber: "3280", category: "AIO Computer" },
  { name: "HP Laserjet 4200n", modelNumber: "4200n", category: "Printer" },
  { name: "Dell Latitude 5580", modelNumber: "Latitude 5580", category: "Laptop Computer" },
  { name: "Dell Optiplex 3080", modelNumber: "Optiplex 3080", category: "Desktop Computer" },
  { name: "ELO Touch Systems", modelNumber: "", category: "Monitor" },
  { name: "Honeywell", modelNumber: "MS7120", category: "Scanners" },
  { name: "Dell Optiplex 7410", modelNumber: "Optiplex 7410", category: "AIO Computer" },
  { name: "Dell E1916H", modelNumber: "E1916H", category: "Monitor" },
  { name: "DREMEL 3D Printer 3D40", modelNumber: "3D40", category: "3D Printer" },
  { name: "HP Color Laserjet CP4025", modelNumber: "CP4025", category: "Printer" },
  { name: "Samsung 70\"", modelNumber: "", category: "Televison" },
  { name: "Dell 19\" TV", modelNumber: "W138", category: "Televison" },
  { name: "InFocus Board", modelNumber: "", category: "Interactive Flat Panel" },
  { name: "Epson Pro G7500U", modelNumber: "G7500U", category: "Projector" },
  { name: "Lenovo ThinkCentre 50a 42 Gen 5", modelNumber: "ThinkCentre 50a 42 Gen 5", category: "AIO Computer" },
  { name: "Brother ADS-1500w", modelNumber: "Ads-1500w", category: "Scanners" },
  { name: "Dell Optiplex 3070", modelNumber: "Optiplex 3070", category: "Desktop Computer" },
  { name: "UC360", modelNumber: "UC360", category: "Phone" },
  { name: "Dell Latitude 3440", modelNumber: "Latitude 3440", category: "Laptop Computer" },
  { name: "EPSON ES-C220", modelNumber: "ES-C220", category: "Scanners" },
  { name: "Dell Latitude 3500", modelNumber: "Latitude 3500", category: "Laptop Computer" },
  { name: "SBID-MX075-V3", modelNumber: "SBID-MX075-V3", category: "Interactive Flat Panel" },
  { name: "Dell Latitude 5320", modelNumber: "Latitude 5320", category: "Laptop Computer" },
  { name: "Sony STR-DH190", modelNumber: "STR-DH190", category: "Sound System" },
  { name: "Polkaudio TSi300", modelNumber: "TSi300", category: "Sound System" },
  { name: "SBID-MX075-V2", modelNumber: "SBID-MX075-V2", category: "Interactive Flat Panel" },
  { name: "Panasonic LB 90 XGA", modelNumber: "LB 90 XGA", category: "Projector" },
  { name: "EPSON EX3280", modelNumber: "EX3280", category: "Projector" },
  { name: "NEC M260X", modelNumber: "M260X", category: "Projector" },
  { name: "Dell Optiplex-5270", modelNumber: "Optiplex-5270", category: "AIO Computer" },
  { name: "SBID-MX075-V1", modelNumber: "SBID-MX075-V1", category: "Interactive Flat Panel" },
  { name: "NEC M271X", modelNumber: "M271X", category: "Projector" },
  { name: "Lenovo ThinkCentre M70a Gen3", modelNumber: "ThinkCentre M70a Gen3", category: "AIO Computer" },
  { name: "Brother ADS-1200", modelNumber: "ADS-1200", category: "Scanners" },
  { name: "Insignia NS-32E321A13", modelNumber: "NS-32E321A13", category: "Televison" },
  { name: "NEC V311W", modelNumber: "V311W", category: "Projector" },
  { name: "Dell Optiplex 7010", modelNumber: "Optiplex 7010", category: "Desktop Computer" },
  { name: "Epson Powerlite 992f", modelNumber: "Powerlite 992f", category: "Projector" },
  { name: "Samsung UN65TU800fXZA", modelNumber: "UN65TU800fXZA", category: "Televison" },
  { name: "Edifier E10", modelNumber: "E10", category: "Sound System" },
  { name: "HP Color Laser Jet Enterprise M455", modelNumber: "M455", category: "Printer" },
  { name: "SBID-MX065-V1", modelNumber: "SBID-MX065-V1", category: "Interactive Flat Panel" },
  { name: "Lenovo Thinkstation P360", modelNumber: "Thinkstation P360", category: "Desktop Computer" },
  { name: "E2211Hc", modelNumber: "E2211Hc", category: "Monitor" },
  { name: "Dell P2714HC", modelNumber: "P2714HC", category: "Monitor" },
  { name: "Philips 50PFL3707", modelNumber: "50PFL3707", category: "Televison" },
  { name: "Yamaha StagePAS 300", modelNumber: "StagePAS 300", category: "Sound System" },
  { name: "SENNHEISER EW DIGITAL", modelNumber: "EW DIGITAL", category: "Sound System" },
  { name: "SENNHEISER E835", modelNumber: "E835", category: "Sound System" },
  { name: "Bretford Cart 4Wheel", modelNumber: "Cart 4Wheel", category: "Cart" },
  { name: "Lenovo Thinkpad P15s Gen 1", modelNumber: "P15s Gen 1", category: "Laptop Computer" },
  { name: "Dell Precision 3430", modelNumber: "Precision 3430", category: "Desktop Computer" },
  { name: "Dell Precision 3260", modelNumber: "Precision 3260", category: "Desktop Computer" },
  { name: "Cirrus Media Player", modelNumber: "Media Player", category: "Media Player" },
  { name: "LG 55\" Television", modelNumber: "55\" Television", category: "Televison" },
  { name: "Vizio D40f-E1", modelNumber: "D40f-E1", category: "Televison" },
  { name: "SHARP LC-42LB261U", modelNumber: "LC-42LB261U", category: "Televison" },
  { name: "Smart MX065-V2", modelNumber: "MX065-V2", category: "Interactive Flat Panel" },
  { name: "Dell e198wfpf", modelNumber: "e198wfpf", category: "Monitor" },
  { name: "Samsung 55\"", modelNumber: "55\"", category: "Televison" },
  { name: "ASUS VS207", modelNumber: "VS207", category: "Monitor" },
  { name: "EPSON VS230", modelNumber: "VS230", category: "Projector" },
  { name: "HP Laserjet p1102w", modelNumber: "p1102w", category: "Printer" },
  { name: "Smart Board E70", modelNumber: "E70", category: "Interactive Flat Panel" },
  { name: "FlashForge Adventure 5M Pro", modelNumber: "5M Pro", category: "3D Printer" },
  { name: "HP Laserjet P3015", modelNumber: "P3015", category: "Printer" },
  { name: "neo 50q Gen 4", modelNumber: "12LN", category: "Desktop Computer" },
  { name: "Laserjet Pro MFP 4301fdn", modelNumber: "Laserjet Pro MFP 4301fdn", category: "Printer" },
  { name: "DiskStation DS1823xs+", modelNumber: "DS1823xs+", category: "Network Infrastructure" },
  { name: "Chrome 500e 2in1 G5 M89", modelNumber: "Chrome 500e 2in1 G5 M89", category: "Chromebook" },
  { name: "Chrome 100e G5 M89", modelNumber: "Chrome 100e G5 M89", category: "Chromebook" },
  { name: "iPhone 17e", modelNumber: "MHRN4LL/A", category: "Smartphone" },
  { name: "MacBook Pro", modelNumber: "A3112", category: "Laptop Computer" },
  { name: "E2425HSM", modelNumber: "E2425HSM", category: "Monitor" },
  { name: "Epson DS-860", modelNumber: "DS-860", category: "Scanners" },
  { name: "AIPHONE IX-MV", modelNumber: "IX-MV", category: "Security" },
  { name: "DYMO LabelWriter 450 Turbo", modelNumber: "LabelWriter 450 Turbo", category: "Printer" },
  { name: "Jujitsu ScanSnap iX500", modelNumber: "ScanSnap iX500", category: "Scanners" },
  { name: "Gemalto CR5400", modelNumber: "CR5400", category: "Scanners" },
  { name: "InFocus INF55K1MB", modelNumber: "INF55K1MB", category: "Interactive Flat Panel" },
  { name: "Dell U2417H", modelNumber: "U2417H", category: "Monitor" },
  { name: "Sony TV", modelNumber: "Sony 85 inch tv", category: "Televison" },
  { name: "HP LaserJet Pro MFP M227fdw", modelNumber: "LaserJet Pro MFP M227fdw", category: "Printer" },
  { name: "ID Maker Zenius", modelNumber: "ID Maker Zenius", category: "Printer" },
  { name: "ViewSonic VA3209M", modelNumber: "VA3209M", category: "Monitor" },
  { name: "Lenovo", modelNumber: "500e 2-in-1 Gen 5", category: "Chromebook" },
  { name: "iMac", modelNumber: "Mac16,3", category: "Desktop Computer" },
  { name: "Chromebook Cart", modelNumber: "", category: "Cart" },
  { name: "Chromebook Cart", modelNumber: "InTouch32", category: "Cart" },
  { name: "Chromebook Lenovo 300e", modelNumber: "300e", category: "Chromebook" },
  { name: "ThinkCentre neo 50a 27 Gen 5", modelNumber: "ThinkCentre neo 50a 27 Gen 5", category: "AIO Computer" },
  { name: "iPad (A16) Wi-Fi", modelNumber: "MD4D4LL/A", category: "Tablet" },
  { name: "tp-link 5-Port Gigabit Switch", modelNumber: "TL-SG105", category: "Unmanaged Network Switch" },
  { name: "tp-link Omada", modelNumber: "POE150S", category: "Power Injector (PoE)" },
  { name: "GS308", modelNumber: "GS308", category: "Unmanaged Network Switch" },
];
